# NNDL HW3
## sajjad pakdaman savoji
### 810195517

# Q2-1

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import copy

In [3]:
def sgn(x):
    return 2*(x>=0) - 1

In [21]:
A = np.array([1, 1, 1, -1])
A = A.reshape(-1, 1)

In [22]:
WA = np.matmul(A, A.T) - np.eye(len(A) ,dtype='int')
W = WA

In [23]:
apred = sgn(np.matmul(A.T, W)).T
apred

array([[ 1],
       [ 1],
       [ 1],
       [-1]])

# Q2-2

In [24]:
B  = np.array([1, 1, -1, 1]).reshape(-1, 1)
WB = np.matmul(B, B.T) - np.eye(len(B) ,dtype='int')
W  += WB

In [25]:
apred = sgn(np.matmul(A.T, W)).T
apred

array([[ 1],
       [ 1],
       [ 1],
       [-1]])

In [26]:
bpred = sgn(np.matmul(B.T, W)).T
bpred

array([[ 1],
       [ 1],
       [-1],
       [ 1]])

# Q2-3

In [27]:
C  = np.array([1, -1, 1, 1]).reshape(-1, 1)
WC = np.matmul(C, C.T) - np.eye(len(C) ,dtype='int')
W  += WC

In [28]:
apred = sgn(np.matmul(A.T, W)).T
apred

array([[ 1],
       [ 1],
       [ 1],
       [-1]])

In [29]:
bpred = sgn(np.matmul(B.T, W)).T
bpred

array([[ 1],
       [ 1],
       [-1],
       [ 1]])

In [30]:
cpred = sgn(np.matmul(C.T, W)).T
cpred

array([[ 1],
       [-1],
       [ 1],
       [ 1]])

# Q2-4

In [32]:
D  = np.array([-1, 1, 1, 1]).reshape(-1, 1)
WD = np.matmul(D, D.T) - np.eye(len(D) ,dtype='int')
W  += WD

In [33]:
apred = sgn(np.matmul(A.T, W)).T
apred

array([[1],
       [1],
       [1],
       [1]])

In [34]:
bpred = sgn(np.matmul(B.T, W)).T
bpred

array([[1],
       [1],
       [1],
       [1]])

In [35]:
cpred = sgn(np.matmul(C.T, W)).T
cpred

array([[1],
       [1],
       [1],
       [1]])

In [36]:
dpred = sgn(np.matmul(D.T, W)).T
dpred

array([[1],
       [1],
       [1],
       [1]])