# NNDL HW3
## sajjad pakdaman savoji
### 810195517

# Q3-1

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import copy

In [2]:
def sgn(x):
    return 2*(x>=0) - 1

In [3]:
def psgn(x):
    y = 2*(x>=0) - 1
    y[x == 0] = x[x==0]
    return y

In [24]:
def ppsgn(x , z):
    y = 2*(x>=0) - 1
    y[x == 0] = z[x==0]
    return y

In [30]:
A = np.array([1, 1, 1, -1], dtype='float')
A = A.reshape(-1, 1)

In [37]:
WA = np.matmul(A, A.T) - np.eye(len(A) ,dtype='float')
W = WA

In [38]:
apred = sgn(np.matmul(A.T, W)).T
apred

array([[ 1],
       [ 1],
       [ 1],
       [-1]])

# Q3-2

In [39]:
m1 = np.array([0, 0, 0, -1], dtype='float').reshape(-1, 1)
m2 = np.array([1, 0, 0, 0] , dtype='float').reshape(-1, 1)
m3 = np.array([0, 1, 0, 0] , dtype='float').reshape(-1, 1)
m4 = np.array([0, 0, 1, 0] , dtype='float').reshape(-1, 1)

In [40]:
pred = ppsgn(np.matmul(m1.T, W).T , m1)
print(pred)

[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [41]:
pred = ppsgn(np.matmul(m2.T, W).T, m2)
pred

array([[ 1],
       [ 1],
       [ 1],
       [-1]])

In [42]:
pred = ppsgn(np.matmul(m3.T, W).T, m3)
pred

array([[ 1],
       [ 1],
       [ 1],
       [-1]])

In [43]:
pred = ppsgn(np.matmul(m4.T, W).T , m4)
pred

array([[ 1],
       [ 1],
       [ 1],
       [-1]])

# Q3-3

In [44]:
n1 = np.array([-1, -1, -1, -1]).reshape(-1, 1)
n2 = np.array([1, -1, -1, 1]).reshape(-1, 1)
n3 = np.array([-1, 1, -1, 1]).reshape(-1, 1)
n4 = np.array([-1, -1, 1, 1]).reshape(-1, 1)

In [46]:
pred = ppsgn(np.matmul(n1.T, W).T , n1)
print(pred)
pred = ppsgn(np.matmul(pred.T, W).T, pred[::])
print(pred)

[[-1]
 [-1]
 [-1]
 [ 1]]
[[-1]
 [-1]
 [-1]
 [ 1]]


In [47]:
pred = sgn(np.matmul(n2.T, W)).T
pred

array([[-1],
       [-1],
       [-1],
       [ 1]])

In [48]:
pred = sgn(np.matmul(n3.T, W)).T
pred

array([[-1],
       [-1],
       [-1],
       [ 1]])

In [49]:
pred = sgn(np.matmul(n4.T, W)).T
pred

array([[-1],
       [-1],
       [-1],
       [ 1]])

# Q3-4 missing

In [50]:
mask = np.array([0, 1, 2, 3])
np.random.shuffle(mask)
print(mask)
m1p = copy.deepcopy(m1)
for m in mask:
    pred = psgn(np.matmul(m1p.T, W) + m1p.T).T
    m1p[m] = pred[m]
    print(m1p)

[1 0 2 3]
[[ 0.]
 [ 1.]
 [ 0.]
 [-1.]]
[[ 1.]
 [ 1.]
 [ 0.]
 [-1.]]
[[ 1.]
 [ 1.]
 [ 1.]
 [-1.]]
[[ 1.]
 [ 1.]
 [ 1.]
 [-1.]]


In [51]:
mask = np.array([0, 1, 2, 3])
np.random.shuffle(mask)
print(mask)
m1p = copy.deepcopy(m2)
for m in mask:
    pred = psgn(np.matmul(m1p.T, W) + m1p.T).T
    m1p[m] = pred[m]
    print(m1p)

[3 0 2 1]
[[ 1.]
 [ 0.]
 [ 0.]
 [-1.]]
[[ 1.]
 [ 0.]
 [ 0.]
 [-1.]]
[[ 1.]
 [ 0.]
 [ 1.]
 [-1.]]
[[ 1.]
 [ 1.]
 [ 1.]
 [-1.]]


In [52]:
mask = np.array([0, 1, 2, 3])
np.random.shuffle(mask)
print(mask)
m1p = copy.deepcopy(m3)
for m in mask:
    pred = psgn(np.matmul(m1p.T, W) + m1p.T).T
    m1p[m] = pred[m]
    print(m1p)

[0 2 1 3]
[[1.]
 [1.]
 [0.]
 [0.]]
[[1.]
 [1.]
 [1.]
 [0.]]
[[1.]
 [1.]
 [1.]
 [0.]]
[[ 1.]
 [ 1.]
 [ 1.]
 [-1.]]


In [53]:
mask = np.array([0, 1, 2, 3])
np.random.shuffle(mask)
print(mask)
m1p = copy.deepcopy(m4)
for m in mask:
    pred = psgn(np.matmul(m1p.T, W) + m1p.T).T
    m1p[m] = pred[m]
    print(m1p)

[2 3 0 1]
[[0.]
 [0.]
 [1.]
 [0.]]
[[ 0.]
 [ 0.]
 [ 1.]
 [-1.]]
[[ 1.]
 [ 0.]
 [ 1.]
 [-1.]]
[[ 1.]
 [ 1.]
 [ 1.]
 [-1.]]


# Q3-4 noise

In [42]:
mask = np.array([0, 1, 2, 3])
np.random.shuffle(mask)
print(mask)
m1p = copy.deepcopy(n1)
for m in mask:
    pred = psgn(np.matmul(m1p.T, W) + m1p.T).T
    m1p[m] = pred[m]
    print(m1p)

[3 1 0 2]
[[-1]
 [-1]
 [-1]
 [ 1]]
[[-1]
 [-1]
 [-1]
 [ 1]]
[[-1]
 [-1]
 [-1]
 [ 1]]
[[-1]
 [-1]
 [-1]
 [ 1]]


In [43]:
mask = np.array([0, 1, 2, 3])
np.random.shuffle(mask)
print(mask)
m1p = copy.deepcopy(n2)
for m in mask:
    pred = psgn(np.matmul(m1p.T, W) + m1p.T).T
    m1p[m] = pred[m]
    print(m1p)

[0 3 2 1]
[[-1]
 [-1]
 [-1]
 [ 1]]
[[-1]
 [-1]
 [-1]
 [ 1]]
[[-1]
 [-1]
 [-1]
 [ 1]]
[[-1]
 [-1]
 [-1]
 [ 1]]


In [44]:
mask = np.array([0, 1, 2, 3])
np.random.shuffle(mask)
print(mask)
m1p = copy.deepcopy(n3)
for m in mask:
    pred = psgn(np.matmul(m1p.T, W) + m1p.T).T
    m1p[m] = pred[m]
    print(m1p)

[2 3 1 0]
[[-1]
 [ 1]
 [-1]
 [ 1]]
[[-1]
 [ 1]
 [-1]
 [ 1]]
[[-1]
 [-1]
 [-1]
 [ 1]]
[[-1]
 [-1]
 [-1]
 [ 1]]


In [45]:
mask = np.array([0, 1, 2, 3])
np.random.shuffle(mask)
print(mask)
m1p = copy.deepcopy(n4)
for m in mask:
    pred = psgn(np.matmul(m1p.T, W) + m1p.T).T
    m1p[m] = pred[m]
    print(m1p)

[1 0 2 3]
[[-1]
 [-1]
 [ 1]
 [ 1]]
[[-1]
 [-1]
 [ 1]
 [ 1]]
[[-1]
 [-1]
 [-1]
 [ 1]]
[[-1]
 [-1]
 [-1]
 [ 1]]
